### PR TITLE
Poster changes

### PR DESCRIPTION
**Pull request by eric2302**
Hey @CPernet, thanks for including the figure from @DrCyPhi. I've made some slight changes to the poster text. Can any of you make me a contributor so that I can merge these changes?

### CODE REVIEW

**Comment by DrCyPhi** [comment]
Thanks Cyril! Looks good! Just got back from a long meeting.

**Comment by mathesong** [comment]
Hi all,

I promised to provide figures. I wasn't 100% clear on what you wanted figures of (I think I drifted off a little bit during the meeting - apologies!), but I've provided a few options where I've put some things together.

Here's a simple png with a horizontal plot of the blood processing on the left and the kinetic modelling on the right:
kinfitr_bloodstream_horizontal

I've also got the same plots in both a horizontal and vertical orientation in which it's editable in case that's not quite what you're looking for here:
kinfitr_figs

And, regarding what you want to put on the poster and/or what you want to say, the plot with the Outcomes legend comes from bloodstream (and also kinfitr: bloodstream is just a BIDS app built on the blood processing functionality in kinfitr), for processing blood; and the plot on the right comes from kinfitr, and is a PET model fit to a time-activity curve.

So if you want to only talk about kinfitr, you can use the right or both plots, or if you want to only talk about bloodstream for blood processing you could use the left plot, or if you want to talk about both, you can say that left is from bloodstream and right is kinfitr.

Text along the lines of the following:

> bloodstream (left) for blood processing, and kinfitr (right) for kinetic modelling and quantification.

Happy to look it anything over if you're uncertain of the wording.

**Comment by eric2302** [comment]
Thanks for the details @mathesong. I put your figures in the newest commit [#1cdb9a5](https://github.com/openneuropet/outreach/commit/1cdb9a518cf38e8c438ef6eef975b438164be9d1) with references to your repos. @mnoergaard I also added a basic workflow chart for petprep/petsurfer into the poster

**Comment by eric2302** [comment]
Thanks again @mathesong! I added the new chart to the poster (see latest push)

**Pull request merged**
